title: Commutators and Capacitors
author: spuriosity1
subtitle: Jack of all Trades, Master of None

url: "https://spuriosity1.github.io"
baseurl: ""


footer_only_homepage: true
footer_url: "https://github.com/Spuriosity1"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

highlighter: rouge


navbar:
 - name: "About"
   link: "about"

