title: Commutators and Capacitors
author: spuriosity1
subtitle: Jack of all Trades, Master of None

url: "https://spuriosity1.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/Spuriosity1"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

plugins:
 - jekyll-katex

navbar:
 - name: "About"
   link: "about"

katex:
  js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor
